/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pstu;

import Pstu.Conponent.*;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ASUS
 */
public class addStudent extends javax.swing.JFrame {

    /**
     * Creates new form adminTeacher
     */
    
   public int check = 1;
   
   public String dateFromDatePicker = "";
   ArrayList<String> column = new ArrayList<String>();
   
   
    public addStudent() {
        initComponents();
    }
    

     
    
    public  void alert(String check, String mes){
        if("false".equals(check)){
            alert.setVisible(false);
            alertLogo.setVisible(false);
            alertClose.setVisible(false);
            alert.setBackground(Color.white);
            alertText.setText("");
        }else{
            alert.setVisible(true);
            alertLogo.setVisible(true);
            alertClose.setVisible(true);
            alert.setBackground(new Color(102,0,102));
            alertText.setText(mes); 
        }
    }
    
    public  void alertSuccess(String mes){
        alertSuccess.setVisible(true);
        alertSuccessText.setText(mes);
        alertsuccessLogo.setVisible(true);
        alertSuccessClose.setVisible(true);
    }
    
    
    
    public  int onlyDigits(String id)
    {
        int pass = 1;
            for (int i = 0; i < id.length(); i++) {
                if (id.charAt(i) >= '0' && id.charAt(i) <= '9') {
                    alert("false",""); 
                }
                else {
                    pass = 0;
                    alert("true","wrong insert ! Check nid,id,reg field");
                    break;
                }
            }
            return pass;
    }
    
    
    public boolean onlyString(String s)
    {
           if(s.matches("[a-zA-Z]+")){
               alert("false","");
           }else{
               alert("true","wrong insert ! Check name,fname,mname field"); 
               return false;
           }
            return true;
    }
    
    public boolean count(String s, int n, String msg)
    {
           if(s.length()==n){
               alert("false","");
           }else{
               alert("true",msg); 
               return false;
           }
            return true;
    }
        
    
    public void resetField(){
       nameVal.setText("");
       fnameVal.setText("");
       mnameVal.setText("");
       addrVal.setText("");
       nidVal.setText("");
       idVal.setText("");
       regVal.setText("");
       sessionVal.setSelectedIndex(0);
       bloodVal.setSelectedIndex(0);
       facVal.setSelectedIndex(0);
       hallVal.setSelectedIndex(0);
    }
    
    
    
     public void insertStudent(ArrayList<String> languages){
         String[] data = new String[languages.size()];
         data = languages.toArray(data);

            try{
                conn cc = new conn();
                
                    String query = "INSERT INTO `student`(`name`, `fname`, `mname`, `addr`, `nid`,`dob`, `roll`, `reg`, `session`, `blood`, `fac`, `hall`) "
                            + "VALUES ('"+data[0]+"','"+data[1]+"','"+data[2]+"','"+data[3]+"','"+data[4]+"','"+data[5]+"','"+data[6]+"','"+data[7]+"','"+data[8]+"','"+data[9]+"','"+data[10]+"','"+data[11]+"')";
                    int i = cc.s.executeUpdate(query);
                    if(i==1){
                        alertSuccess("Woo! Student Added Successfully");
                    }           
            }catch(SQLException ee){
                System.out.println("The error is:"+ee);
            }
     }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        adminTeacherPanel = new javax.swing.JPanel();
        bottomrightborder = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameVal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fnameVal = new javax.swing.JTextField();
        mnameVal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addrVal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nidVal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        idVal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        regVal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        hallVal = new javax.swing.JComboBox<>();
        sessionVal = new javax.swing.JComboBox<>();
        facVal = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        alertSuccessClose = new javax.swing.JButton();
        alertClose = new javax.swing.JButton();
        alertsuccessLogo = new javax.swing.JLabel();
        alertLogo = new javax.swing.JLabel();
        alertSuccessText = new javax.swing.JLabel();
        alertText = new javax.swing.JLabel();
        alertSuccess = new javax.swing.JLabel();
        alert = new javax.swing.JLabel();
        bloodVal = new javax.swing.JComboBox<>();
        dobVal = new com.toedter.calendar.JDateChooser();
        background = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(634, 80));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        adminTeacherPanel.setBackground(new java.awt.Color(0, 204, 204));
        adminTeacherPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                adminTeacherPanelComponentShown(evt);
            }
        });
        adminTeacherPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bottomrightborder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/vactorimage/border right bottom - Copy - Copy.png"))); // NOI18N
        adminTeacherPanel.add(bottomrightborder, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 330, 340));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_undo_35px.png"))); // NOI18N
        close.setText("  Back");
        close.setBorder(null);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        adminTeacherPanel.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/vactorimage/addNew Student.png"))); // NOI18N
        adminTeacherPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 84, 680, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Name");
        adminTeacherPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 60, 40));

        nameVal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nameVal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nameVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameValActionPerformed(evt);
            }
        });
        adminTeacherPanel.add(nameVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 300, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Father Name");
        adminTeacherPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 110, 40));

        fnameVal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        fnameVal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fnameVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameValActionPerformed(evt);
            }
        });
        adminTeacherPanel.add(fnameVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 300, 40));

        mnameVal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mnameVal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mnameVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameValActionPerformed(evt);
            }
        });
        adminTeacherPanel.add(mnameVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 300, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mother Name");
        adminTeacherPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 120, 40));

        addrVal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        addrVal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addrVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrValActionPerformed(evt);
            }
        });
        adminTeacherPanel.add(addrVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 300, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Address");
        adminTeacherPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 80, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Nid No ");
        adminTeacherPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 70, 40));

        nidVal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nidVal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nidVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nidValActionPerformed(evt);
            }
        });
        adminTeacherPanel.add(nidVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 300, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Id");
        adminTeacherPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 30, 40));

        idVal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        idVal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        idVal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idValFocusLost(evt);
            }
        });
        idVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idValActionPerformed(evt);
            }
        });
        idVal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idValKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idValKeyTyped(evt);
            }
        });
        adminTeacherPanel.add(idVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 300, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Reg");
        adminTeacherPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 40, 40));

        regVal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        regVal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        regVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regValActionPerformed(evt);
            }
        });
        adminTeacherPanel.add(regVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 300, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Session");
        adminTeacherPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 70, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Birth Date");
        adminTeacherPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 90, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Blood");
        adminTeacherPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 50, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText(":");
        adminTeacherPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 20, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText(":");
        adminTeacherPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 20, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText(":");
        adminTeacherPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 20, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText(":");
        adminTeacherPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 20, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText(":");
        adminTeacherPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 20, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText(":");
        adminTeacherPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 20, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText(":");
        adminTeacherPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 20, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText(":");
        adminTeacherPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 20, 40));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText(":");
        adminTeacherPanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 20, 40));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText(":");
        adminTeacherPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 20, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Hall");
        adminTeacherPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 40, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText(":");
        adminTeacherPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 20, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Faculty");
        adminTeacherPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 60, 40));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText(":");
        adminTeacherPanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 20, 40));

        hallVal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        hallVal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Sher-E-Bangla Hall 1", "Sher-E-Bangla Hall 2", "Keramat Ali Hall", "Bangabandhu Sheikh Mujibor Rahman Hall", "Kobi Begum Sufia Kamal Hall", "Sheikh Fajilatunnesa Mujib Hall", "Captain Mohiuddin Jahangir Hall", "Sheikh Fajilatunnesa Mujib Hall-Babuganj", " " }));
        adminTeacherPanel.add(hallVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 300, 40));

        sessionVal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        sessionVal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "2015-2106", "2016-2017", "2017-2018", "2018-2019", "2019-2020", "2020-2021", "2021-2022", "2022-2023", "2023-2024", "2024-2025", "2025-2026", " " }));
        adminTeacherPanel.add(sessionVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 300, 40));

        facVal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        facVal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Computer Science & Engineering", "Agriculture", "Business Administration", "Animal Science and Veterinary Medicine", "Fisheries", "Environmental Science and Disaster Management", "Nutrition and Food Science", "Land Management and Administration" }));
        adminTeacherPanel.add(facVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 300, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        jButton1.setText(" Add New");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        adminTeacherPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 150, 40));

        alertSuccessClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/university/management/system/icons/Button/icons8_Close_35px.png"))); // NOI18N
        alertSuccessClose.setBorder(null);
        alertSuccessClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alertSuccessClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertSuccessCloseActionPerformed(evt);
            }
        });
        adminTeacherPanel.add(alertSuccessClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 25, 40, 40));

        alertClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/university/management/system/icons/Button/icons8_Close_35px.png"))); // NOI18N
        alertClose.setBorder(null);
        alertClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alertClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertCloseActionPerformed(evt);
            }
        });
        adminTeacherPanel.add(alertClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 25, 40, 40));

        alertsuccessLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/university/management/system/icons/Button/checkToast.png"))); // NOI18N
        alertsuccessLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminTeacherPanel.add(alertsuccessLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 50, 50));

        alertLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/university/management/system/icons/Button/icons8_warning_shield_35px.png"))); // NOI18N
        alertLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminTeacherPanel.add(alertLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 50, 50));

        alertSuccessText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alertSuccessText.setForeground(new java.awt.Color(255, 255, 255));
        adminTeacherPanel.add(alertSuccessText, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 360, 50));

        alertText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alertText.setForeground(new java.awt.Color(255, 255, 255));
        adminTeacherPanel.add(alertText, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 380, 50));

        alertSuccess.setBackground(new java.awt.Color(0, 91, 19));
        alertSuccess.setOpaque(true);
        adminTeacherPanel.add(alertSuccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 490, 70));

        alert.setBackground(new java.awt.Color(102, 0, 102));
        alert.setOpaque(true);
        adminTeacherPanel.add(alert, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 490, 70));

        bloodVal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bloodVal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "A +", "A -", "B +", "B -", "O +", "O -", "AB +", "AB -", " " }));
        adminTeacherPanel.add(bloodVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 300, 40));

        dobVal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        dobVal.setDateFormatString("dd-MM-yyyy");
        dobVal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dobValMouseClicked(evt);
            }
        });
        dobVal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dobValPropertyChange(evt);
            }
        });
        adminTeacherPanel.add(dobVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 300, 40));

        background.setBackground(new java.awt.Color(0, 153, 153));
        background.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/1115855.png"))); // NOI18N
        background.setToolTipText("");
        background.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        background.setOpaque(true);
        adminTeacherPanel.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1115, 855));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminTeacherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(adminTeacherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminTeacherPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_adminTeacherPanelComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_adminTeacherPanelComponentShown

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void nameValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameValActionPerformed

    private void fnameValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameValActionPerformed

    private void mnameValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameValActionPerformed

    private void addrValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrValActionPerformed

    private void nidValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nidValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nidValActionPerformed

    private void idValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idValActionPerformed

    private void regValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regValActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = nameVal.getText();
        String fname = fnameVal.getText();
        String mname = mnameVal.getText();
        String id = idVal.getText();
        String reg =  regVal.getText();
        String addr = addrVal.getText();
        String nid =  nidVal.getText();
        String session =  (String)sessionVal.getSelectedItem();
        String fac = (String)facVal.getSelectedItem();
        String hall = (String)hallVal.getSelectedItem();
        String blood = (String)bloodVal.getSelectedItem();
        String dob = dateFromDatePicker;
             

        
        String regexAlphabet = "^[A-Za-z_ ]+$";
        String regexNumber = "^[0-9]+$";
        
        
        
        if(name.matches(regexAlphabet)){ // Check name,fname,mname only have Alpahabet or not
            column.add(name);
            if(fname.matches(regexAlphabet)){ 
                column.add(fname);
                if(mname.matches(regexAlphabet)){ 
                    column.add(mname);
                    if(!"".equals(addr)){
                        column.add(addr);
                        if(nid.matches(regexNumber)){ // Check nid only have digits or not
                            if(count(nid,10,"Nid no sholuld be 10 digit") == true){ // Call count() meathoad with three arguements
                                column.add(nid);
                                if(!"".equals(dob)){
                                    column.add(dob);
                                    if(id.matches(regexNumber)){
                                        if(count(id,7,"Id no sholuld be 7 digit") == true){
                                            column.add(id);
                                            if(reg.matches(regexNumber)){
                                                if(count(reg,5,"Reg no sholuld be 5 digit") == true){
                                                    column.add(reg);
                                                    if(!"Select one".equals(session)){
                                                        column.add(session);
                                                        if(!"Select one".equals(blood)){
                                                            column.add(blood);
                                                            if(!"Select one".equals(fac)){
                                                                column.add(fac);
                                                                if(!"Select one".equals(hall)){
                                                                column.add(hall);
                                                                 //  If Everything is ok lets begain insert data into database
                                                                  insertStudent(column);
                                                                  resetField();
                                                                }else{alert("true","Select student Residence hall");}
                                                            }else{alert("true","Select student Faculty");}
                                                        }else{alert("true","Select student Blood group");}
                                                    }else{alert("true","Select student Session");}
                                                }
                                            }else{alert("true","You insert wrong Registration number");}
                                        }
                                    }else{alert("true","You insert wrong Id");}

                                }else{ alert("true","Select Birth Date");}
                            }
                        }else{alert("true","You insert wrong Nid");}                       
                    }else{alert("true","Insert Address");}
                }else{alert("true","Mother name should be alpahbet");}
            }else{alert("true","Fataher name should be alpahbet");}
        }else{alert("true","Name should be alpahbet");}
        
       
        
//            try{
//                conn cc = new conn();
//                if(name.equals("") || fname.equals("")|| mname.equals("")|| id.equals("") || reg.equals("")|| dob.equals("")|| addr.equals("")|| fac.equals("")|| hall.equals("")|| blood.equals("")|| nid.equals("")){
//                        alert("true","Fill up all field"); 
//                }else{
//
//                    if(!formValid.onlyString(name) || formValid.onlyString(fname) || formValid.onlyString(mname)){
//                        alert("false","Wrong insert ! Check carefully");
//                    }
//
//                    String query = "INSERT INTO `student`(`name`, `fname`, `mname`, `addr`, `nid`,`roll`, `reg`, `dob`, `fac`, `hall`, `blood`, `session`) VALUES ('"+name+"','"+fname+"','"+mname+"','"+addr+"','"+nid+"','"+id+"','"+reg+"','"+dob+"','"+fac+"','"+hall+"','"+blood+"','"+session+"')";
//                    int i = cc.s.executeUpdate(query);
//                    if(i==1){
//                      new ToastAlert("Student Added successfully","checkToast.png","delete2.png").setVisible(true);
//                        setVisible(false); 
//                    } 
//                }            
//            }catch(SQLException ee){
//                System.out.println("The error is:"+ee);
//            }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void alertCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertCloseActionPerformed
        // TODO add your handling code here:
        alert("false","");
    }//GEN-LAST:event_alertCloseActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        

        
        nameVal.setBorder(BorderFactory.createCompoundBorder(nameVal.getBorder(), BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        fnameVal.setBorder(BorderFactory.createCompoundBorder(fnameVal.getBorder(), BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        mnameVal.setBorder(BorderFactory.createCompoundBorder(mnameVal.getBorder(), BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        addrVal.setBorder(BorderFactory.createCompoundBorder(addrVal.getBorder(), BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        nidVal.setBorder(BorderFactory.createCompoundBorder(nidVal.getBorder(), BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        dobVal.setBorder(BorderFactory.createCompoundBorder(dobVal.getBorder(), BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        idVal.setBorder(BorderFactory.createCompoundBorder(idVal.getBorder(), BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        regVal.setBorder(BorderFactory.createCompoundBorder(regVal.getBorder(), BorderFactory.createEmptyBorder(6, 6, 6, 6)));
        
        alert.setVisible(false);
        alertText.setText("");
        alertLogo.setVisible(false);
        alertClose.setVisible(false);
        
        alertSuccess.setVisible(false);
        alertSuccessText.setText("");
        alertsuccessLogo.setVisible(false);
        alertSuccessClose.setVisible(false);
    }//GEN-LAST:event_formComponentShown

    private void idValKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idValKeyPressed
        // TODO add your handling code here:
        
       
        
    }//GEN-LAST:event_idValKeyPressed

    private void idValKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idValKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_idValKeyTyped

    private void idValFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idValFocusLost
        // TODO add your handling code here:
        
//        System.out.println("Focus Lost");
    }//GEN-LAST:event_idValFocusLost

    private void dobValMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dobValMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dobValMouseClicked

    private void dobValPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dobValPropertyChange
       if ("date".equals(evt.getPropertyName())){
            Date getDate =  dobVal.getDate();
            DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            dateFromDatePicker = dateFormat.format(getDate);
       }      
    }//GEN-LAST:event_dobValPropertyChange

    private void alertSuccessCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertSuccessCloseActionPerformed
        // TODO add your handling code here:
        
        alertSuccess.setVisible(false);
        alertSuccessText.setText("");
        alertsuccessLogo.setVisible(false);
        alertSuccessClose.setVisible(false);
    }//GEN-LAST:event_alertSuccessCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrVal;
    private javax.swing.JPanel adminTeacherPanel;
    private javax.swing.JLabel alert;
    private javax.swing.JButton alertClose;
    private javax.swing.JLabel alertLogo;
    private javax.swing.JLabel alertSuccess;
    private javax.swing.JButton alertSuccessClose;
    private javax.swing.JLabel alertSuccessText;
    private javax.swing.JLabel alertText;
    private javax.swing.JLabel alertsuccessLogo;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> bloodVal;
    private javax.swing.JLabel bottomrightborder;
    private javax.swing.JButton close;
    private com.toedter.calendar.JDateChooser dobVal;
    private javax.swing.JComboBox<String> facVal;
    private javax.swing.JTextField fnameVal;
    private javax.swing.JComboBox<String> hallVal;
    private javax.swing.JTextField idVal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField mnameVal;
    private javax.swing.JTextField nameVal;
    private javax.swing.JTextField nidVal;
    private javax.swing.JTextField regVal;
    private javax.swing.JComboBox<String> sessionVal;
    // End of variables declaration//GEN-END:variables
}
