/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pstu;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ASUS
 */
public class Board extends javax.swing.JFrame {

    /**
     * Creates new form Board
     */
    public Board() {
        initComponents();
        hide();
    }
    
    
    @Override
    public void hide(){
        adminStudent.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminStudent = new javax.swing.JPanel();
        topleftborder = new javax.swing.JLabel();
        bottomrightborder = new javax.swing.JLabel();
        imageside = new javax.swing.JLabel();
        addNewStudent2 = new javax.swing.JButton();
        studentTablescroll = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        serchIdField = new javax.swing.JTextField();
        addNewStudent1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(634, 80));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1115, 855));
        setSize(new java.awt.Dimension(1115, 855));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        adminStudent.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                adminStudentComponentShown(evt);
            }
        });
        adminStudent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topleftborder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/vactorimage/bordertop left.png"))); // NOI18N
        adminStudent.add(topleftborder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 330, 380));

        bottomrightborder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/vactorimage/border right bottom - Copy - Copy.png"))); // NOI18N
        adminStudent.add(bottomrightborder, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 330, 380));

        imageside.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/vactorimage/adminStudentImage1.png"))); // NOI18N
        adminStudent.add(imageside, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 350, 250));

        addNewStudent2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        addNewStudent2.setText(" Add Student");
        addNewStudent2.setActionCommand("Add Student");
        addNewStudent2.setBorder(null);
        addNewStudent2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addNewStudent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewStudent2ActionPerformed(evt);
            }
        });
        adminStudent.add(addNewStudent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 120, 40));

        studentTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " Session", "Faculty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        studentTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentTable.setRowHeight(35);
        studentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTableMouseClicked(evt);
            }
        });
        studentTablescroll.setViewportView(studentTable);

        adminStudent.add(studentTablescroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 710, 330));

        serchIdField.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        serchIdField.setText("   Search with student id");
        serchIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serchIdFieldActionPerformed(evt);
            }
        });
        adminStudent.add(serchIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 270, 50));

        addNewStudent1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        addNewStudent1.setText("View");
        addNewStudent1.setActionCommand("Add Student");
        addNewStudent1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addNewStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewStudent1ActionPerformed(evt);
            }
        });
        adminStudent.add(addNewStudent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 120, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/1115855.png"))); // NOI18N
        background.setToolTipText("");
        background.setOpaque(true);
        adminStudent.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1115, 855));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(adminStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 1115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(adminStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewStudent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewStudent2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNewStudent2ActionPerformed

    private void studentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTableMouseClicked
        // TODO add your handling code here:

        TableModel table = studentTable.getModel();
        String id = table.getValueAt(0,0).toString();

    }//GEN-LAST:event_studentTableMouseClicked

    private void serchIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serchIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serchIdFieldActionPerformed

    private void addNewStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewStudent1ActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        DefaultTableModel table = (DefaultTableModel)studentTable.getModel();
        int id = studentTable.getSelectedRow();
        String session = table.getValueAt(id,0).toString();
        String fac = table.getValueAt(id,1).toString();
        new AllStudent(session,fac).setVisible(true);
    }//GEN-LAST:event_addNewStudent1ActionPerformed

    private void adminStudentComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_adminStudentComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_adminStudentComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
            conn cc = new conn();
            ResultSet rs = cc.s.executeQuery("select * from student");
             DefaultTableModel table = (DefaultTableModel)studentTable.getModel();
            if(rs.next())
                        System.out.println("Hello");
                  do{
                      String session = rs.getString(10);
                      String fac = rs.getString(14);
                      String st[] = {session,fac};
                      table.addRow(st);
                  }while(rs.next());
            
               rs.close();
               cc.s.close();
               
        }catch(SQLException e){
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Board().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewStudent1;
    private javax.swing.JButton addNewStudent2;
    private javax.swing.JPanel adminStudent;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bottomrightborder;
    private javax.swing.JLabel imageside;
    private javax.swing.JTextField serchIdField;
    private javax.swing.JTable studentTable;
    private javax.swing.JScrollPane studentTablescroll;
    private javax.swing.JLabel topleftborder;
    // End of variables declaration//GEN-END:variables
}
