/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pstu.Conponent;

import Pstu.*;
import java.awt.Cursor;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ASUS
 */
public class adminStudent extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    public String adminUsername ="";
    public adminStudent(String admin) {
        adminUsername = admin;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addNewStudent = new javax.swing.JButton();
        addNewStudent1 = new javax.swing.JButton();
        addNewStudent2 = new javax.swing.JButton();
        imageside = new javax.swing.JLabel();
        studentTablescroll = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        topleftborder = new javax.swing.JLabel();
        bottomrightborder = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(634, 80));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1115, 855));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addNewStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close Jframe.png"))); // NOI18N
        addNewStudent.setText("Close");
        addNewStudent.setActionCommand("Add Student");
        addNewStudent.setBorder(null);
        addNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewStudentActionPerformed(evt);
            }
        });
        getContentPane().add(addNewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 800, 120, 40));

        addNewStudent1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search.png"))); // NOI18N
        addNewStudent1.setText("View");
        addNewStudent1.setActionCommand("Add Student");
        addNewStudent1.setBorder(null);
        addNewStudent1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addNewStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewStudent1ActionPerformed(evt);
            }
        });
        getContentPane().add(addNewStudent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 120, 40));

        addNewStudent2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        addNewStudent2.setText(" Add Student");
        addNewStudent2.setActionCommand("Add Student");
        addNewStudent2.setBorder(null);
        addNewStudent2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addNewStudent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewStudent2ActionPerformed(evt);
            }
        });
        getContentPane().add(addNewStudent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));

        imageside.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/vactorimage/adminStudentImage1.png"))); // NOI18N
        getContentPane().add(imageside, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 350, 250));

        studentTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " Session", "Faculty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        studentTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentTable.setRowHeight(35);
        studentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTableMouseClicked(evt);
            }
        });
        studentTablescroll.setViewportView(studentTable);
        if (studentTable.getColumnModel().getColumnCount() > 0) {
            studentTable.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(studentTablescroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 710, 330));

        topleftborder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/vactorimage/bordertop left.png"))); // NOI18N
        getContentPane().add(topleftborder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 330, 380));
        topleftborder.getAccessibleContext().setAccessibleName("topleftborderimage");

        bottomrightborder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/vactorimage/border right bottom - Copy - Copy.png"))); // NOI18N
        getContentPane().add(bottomrightborder, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 330, 380));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/1115855.png"))); // NOI18N
        background.setToolTipText("");
        background.setOpaque(true);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 855));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_formComponentShown

    private void addNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewStudentActionPerformed
        // TODO add your handling code here:
                        dispose();
    }//GEN-LAST:event_addNewStudentActionPerformed

    private void addNewStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewStudent1ActionPerformed
        // TODO add your handling code here:
        
             this.setVisible(false);
             DefaultTableModel table = (DefaultTableModel)studentTable.getModel();
             int id = studentTable.getSelectedRow();
             String session = table.getValueAt(id,0).toString();
             String fac = table.getValueAt(id,1).toString();
             new AllStudent(session,fac).setVisible(true);
    }//GEN-LAST:event_addNewStudent1ActionPerformed

    private void addNewStudent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewStudent2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNewStudent2ActionPerformed

    private void studentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTableMouseClicked
        // TODO add your handling code here:
        
             TableModel table = studentTable.getModel();
             String id = table.getValueAt(0,0).toString();
        
    }//GEN-LAST:event_studentTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            
            new adminStudent("").setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewStudent;
    private javax.swing.JButton addNewStudent1;
    private javax.swing.JButton addNewStudent2;
    private javax.swing.JLabel background;
    private javax.swing.JLabel bottomrightborder;
    private javax.swing.JLabel imageside;
    private javax.swing.JTable studentTable;
    private javax.swing.JScrollPane studentTablescroll;
    private javax.swing.JLabel topleftborder;
    // End of variables declaration//GEN-END:variables
}
